print("harshavardhan s")
print("i am studying in bms college of engineering ")
print("1bm22cd028")
print("i study in 6th sem ")
print("life is messed up ")
print("wheel of time ")
print("welcome to bmsce")
print("welcome to devops lab test")
